# Generated by Django 4.2.1 on 2023-11-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_owner_user_id_clientuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-id']},
        ),
    ]
