# Generated by Django 4.2.1 on 2023-11-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-id']},
        ),
    ]
