# Generated by Django 4.2.1 on 2023-11-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_owner_id_alter_storeaddress_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-id']},
        ),
    ]
