# Generated by Django 4.2.1 on 2023-11-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_client_user_id_alter_order_coupon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
    ]
